version: "3.8"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: sh -c "npm install && npm start" #that's for live code changes
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: 1 #and this
      CHOKIDAR_POLLINTERVAL: 3000 #and this
    working_dir: /usr/app #and this
    volumes:
      - "./frontend/src:/usr/app/src:cached" #and this

  api:
    build:
      context: ./fam_tree_rest_api
      target: tree_api

  migrator:
    build:
      context: ./fam_tree_rest_api
      target: migrator
